-- FareFlow bootstrap schema
-- Generated from the current Spring Boot / Hibernate model on 2026-03-20

CREATE DATABASE IF NOT EXISTS `fareflow`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `fareflow`;

create table account_charge (end_time time(6), fare_amount decimal(10,2) not null, is_paid bit not null, paid_date date, start_time time(6), tip_amount decimal(10,2), trip_date date not null, cab_id bigint, created_at datetime(6), customer_id bigint not null, driver_id bigint, id bigint not null auto_increment, invoice_id bigint, updated_at datetime(6), account_id varchar(50) not null, invoice_number varchar(50), job_code varchar(50), sub_account varchar(50), passenger_name varchar(100), dropoff_address varchar(300), pickup_address varchar(300), notes varchar(500), primary key (id)) engine=InnoDB;
create table account_credit (credit_amount decimal(38,2) not null, is_active bit, remaining_amount decimal(38,2) not null, used_amount decimal(38,2), created_by bigint, created_date datetime(6) not null, customer_id bigint not null, id bigint not null auto_increment, invoice_id bigint, payment_id bigint, account_id varchar(50) not null, source_type varchar(50) not null, source_reference varchar(100), description varchar(255), primary key (id)) engine=InnoDB;
create table account_customer (credit_limit decimal(10,2), is_active bit not null, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), account_type enum ('CORPORATE','ONE_TIME_USER','PARTY_ACCOUNT','PERSONAL'), billing_period varchar(20), phone_number varchar(20), postal_code varchar(20), account_id varchar(50) not null, country varchar(50), province varchar(50), city varchar(100), contact_person varchar(100), email varchar(100), company_name varchar(200) not null, street_address varchar(200), notes varchar(1000), primary key (id)) engine=InnoDB;
create table airport_trips (grand_total integer not null, hour_00 integer, hour_01 integer, hour_02 integer, hour_03 integer, hour_04 integer, hour_05 integer, hour_06 integer, hour_07 integer, hour_08 integer, hour_09 integer, hour_10 integer, hour_11 integer, hour_12 integer, hour_13 integer, hour_14 integer, hour_15 integer, hour_16 integer, hour_17 integer, hour_18 integer, hour_19 integer, hour_20 integer, hour_21 integer, hour_22 integer, hour_23 integer, trip_date date not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6) not null, upload_date datetime(6), shift varchar(10) not null, cab_number varchar(50) not null, driver_number varchar(50), upload_batch_id varchar(100), uploaded_by varchar(100), vehicle_name varchar(100), upload_filename varchar(255), primary key (id)) engine=InnoDB;
create table attribute_cost (effective_from date not null, effective_to date, price decimal(10,2) not null, attribute_type_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), billing_unit enum ('DAILY','MONTHLY') not null, created_by varchar(255), updated_by varchar(255), primary key (id)) engine=InnoDB;
create table cab (year integer, created_at datetime(6) not null, id bigint not null auto_increment, owner_driver_id bigint, updated_at datetime(6), cab_number varchar(20) not null, status enum ('ACTIVE','INACTIVE') not null, color varchar(30), make varchar(50), model varchar(50), registration_number varchar(50) not null, notes varchar(1000), primary key (id)) engine=InnoDB;
create table cab_attribute_type (is_active bit, requires_value bit, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), category enum ('CERTIFICATION','EQUIPMENT','LICENSE','PERMIT','TYPE') not null, data_type enum ('BOOLEAN','DATE','NUMBER','STRING') not null, attribute_code varchar(50) not null, attribute_name varchar(100) not null, description varchar(500), help_text varchar(500), validation_pattern varchar(255), primary key (id)) engine=InnoDB;
create table cab_attribute_value (end_date date, start_date date not null, attribute_type_id bigint not null, cab_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, shift_id bigint, updated_at datetime(6), created_by varchar(50), updated_by varchar(50), notes varchar(500), attribute_value varchar(255), primary key (id)) engine=InnoDB;
create table cab_owner_history (end_date date, start_date date not null, cab_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, owner_driver_id bigint not null, updated_at datetime(6), notes varchar(500), primary key (id)) engine=InnoDB;
create table cab_shift (airport_license_expiry date, has_airport_license bit, cab_id bigint not null, created_at datetime(6) not null, current_owner_id bigint, current_profile_id bigint, id bigint not null auto_increment, updated_at datetime(6), end_time varchar(10) not null, start_time varchar(10) not null, cab_type enum ('HANDICAP_VAN','SEDAN'), share_type enum ('NON_VOTING_SHARE','VOTING_SHARE'), shift_type enum ('DAY','NIGHT') not null, status enum ('ACTIVE','INACTIVE') not null, airport_license_number varchar(50), notes varchar(500), primary key (id)) engine=InnoDB;
create table commission_category_assignment (assigned_at date not null, is_active bit not null, unassigned_at date, commission_type_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, revenue_category_id bigint not null, updated_at datetime(6), notes varchar(500), primary key (id)) engine=InnoDB;
create table commission_rate (effective_from date not null, effective_to date, is_active bit not null, rate decimal(8,4) not null, commission_type_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), notes varchar(500), primary key (id)) engine=InnoDB;
create table commission_type (is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), code varchar(30) not null, name varchar(100) not null, description varchar(500), primary key (id)) engine=InnoDB;
create table credit_card_transaction (amount decimal(10,2) not null, card_last_four varchar(4), is_refunded bit not null, is_settled bit not null, processing_fee decimal(10,2), refund_amount decimal(10,2), refund_date date, settlement_date date, tip_amount decimal(10,2), transaction_date date not null, transaction_time time(6) not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), upload_date datetime(6), cab_number varchar(20), card_type varchar(20), driver_number varchar(20), transaction_status enum ('DECLINED','DISPUTED','PENDING','REFUNDED','SETTLED') not null, card_brand varchar(30), authorization_code varchar(50) not null, batch_number varchar(50), job_id varchar(50), merchant_id varchar(50) not null, receipt_number varchar(50), terminal_id varchar(50) not null, upload_batch_id varchar(50), customer_name varchar(100), reference_number varchar(100), transaction_id varchar(100) not null, notes varchar(500), upload_filename varchar(255), primary key (id)) engine=InnoDB;
create table driver (deposit_amount float(53), ibc_records_date date, is_admin bit, is_owner bit not null, joined_date date, license_expiry date, pic_date date, refund_date date, security_deposit_date date, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), driver_number varchar(20) not null, emergency_contact_phone varchar(20), phone varchar(20), status enum ('ACTIVE','INACTIVE','SUSPENDED','TERMINATED') not null, emergency_contact_relationship varchar(50), first_name varchar(50) not null, gst_number varchar(50), last_name varchar(50) not null, license_number varchar(50), sin varchar(50), username varchar(50), email varchar(100), emergency_contact_name varchar(100), address varchar(500), notes varchar(1000), password varchar(255), primary key (id)) engine=InnoDB;
create table driver_segment (end_meter_reading decimal(10,2), segment_expenses decimal(10,2), segment_lease_share decimal(10,2), segment_miles decimal(10,2), segment_net_earnings decimal(10,2), segment_revenue decimal(10,2), sequence_number integer not null, start_meter_reading decimal(10,2), created_at datetime(6) not null, driver_id bigint not null, end_time datetime(6), id bigint not null auto_increment, shift_log_id bigint not null, start_time datetime(6) not null, updated_at datetime(6), notes varchar(500), primary key (id)) engine=InnoDB;
create table driver_shifts (primary_shift_count decimal(3,2), secondary_shift_count decimal(3,2), session_count integer, total_distance decimal(10,2), total_hours decimal(5,2), total_revenue decimal(10,2), total_trips integer, created_at datetime(6) not null, created_by bigint, id bigint not null auto_increment, logoff_time datetime(6), logon_time datetime(6) not null, updated_at datetime(6) not null, updated_by bigint, primary_shift_type varchar(10), secondary_shift_type varchar(10), status varchar(20) not null, cab_number varchar(50) not null, driver_number varchar(50) not null, driver_username varchar(50), driver_first_name varchar(100), driver_last_name varchar(100), notes TEXT, session_history JSON, primary key (id)) engine=InnoDB;
create table expense_category (is_active bit, attribute_type_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, shift_profile_id bigint, specific_driver_id bigint, specific_owner_id bigint, specific_person_id bigint, specific_shift_id bigint, updated_at datetime(6), applies_to enum ('CAB','COMPANY','DRIVER','OWNER','SHIFT') not null, category_type enum ('FIXED','VARIABLE') not null, application_type VARCHAR(30) not null, category_code varchar(50) not null, category_name varchar(100) not null, description varchar(500), primary key (id)) engine=InnoDB;
create table expense_category_rule (has_airport_license_rule bit, has_cab_shift_type_rule bit, has_cab_type_rule bit, has_share_type_rule bit, is_active bit, created_at datetime(6) not null, expense_category_id bigint not null, id bigint not null auto_increment, updated_at datetime(6), configuration_mode enum ('AUTO_MATCH','INDIVIDUAL_CONFIG') not null, matching_criteria jsonb, primary key (id)) engine=InnoDB;
create table invoice (amount_paid decimal(10,2) not null, balance_due decimal(10,2) not null, billing_period_end date not null, billing_period_start date not null, due_date date not null, email_send_count integer, invoice_date date not null, previous_balance decimal(10,2), statement_version integer, subtotal decimal(10,2) not null, tax_amount decimal(10,2), tax_rate decimal(5,2), total_amount decimal(10,2) not null, created_at datetime(6) not null, created_by bigint, customer_id bigint not null, id bigint not null auto_increment, last_email_sent_at datetime(6), locked_at datetime(6), locked_by bigint, paid_at datetime(6), parent_statement_id bigint, pdf_generated_at datetime(6), posted_at datetime(6), posted_by bigint, sent_at datetime(6), updated_at datetime(6), status enum ('ARCHIVED','CANCELLED','DRAFT','LOCKED','OVERDUE','PAID','PARTIAL','POSTED','SENT') not null, account_id varchar(50) not null, invoice_number varchar(50) not null, pdf_path varchar(500), terms varchar(500), notes varchar(1000), last_email_sent_to varchar(255), line_items_json JSON, primary key (id)) engine=InnoDB;
create table invoice_line_item (amount decimal(10,2) not null, quantity integer, trip_date date, unit_price decimal(10,2) not null, charge_id bigint not null, id bigint not null auto_increment, invoice_id bigint not null, description varchar(500), primary key (id)) engine=InnoDB;
create table item_rate (effective_from date not null, effective_to date, is_active bit not null, rate decimal(10,4) not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), charged_to enum ('DRIVER','OWNER') not null, unit_type enum ('AIRPORT_TRIP','INSURANCE','MILEAGE') not null, name varchar(100) not null, notes varchar(1000), primary key (id)) engine=InnoDB;
create table item_rate_override (end_date date, is_active bit not null, override_rate decimal(10,4) not null, priority integer not null, start_date date not null, created_at datetime(6), id bigint not null auto_increment, item_rate_id bigint not null, updated_at datetime(6), day_of_week varchar(20), shift_type varchar(20), cab_number varchar(50), created_by varchar(50), owner_driver_number varchar(50) not null, updated_by varchar(50), notes varchar(500), primary key (id)) engine=InnoDB;
create table lease_expense (base_amount decimal(10,2) not null, has_airport_license bit not null, is_paid bit, lease_date date not null, mileage_amount decimal(10,2), miles_driven decimal(10,2), paid_date date, total_amount decimal(10,2) not null, cab_id bigint not null, created_at datetime(6) not null, driver_id bigint not null, id bigint not null auto_increment, plan_id bigint not null, rate_id bigint not null, shift_id bigint, updated_at datetime(6), notes varchar(500), cab_type enum ('HANDICAP_VAN','SEDAN') not null, day_of_week enum ('FRIDAY','MONDAY','SATURDAY','SUNDAY','THURSDAY','TUESDAY','WEDNESDAY') not null, shift_type enum ('DAY','NIGHT') not null, primary key (id)) engine=InnoDB;
create table lease_plan (effective_from date not null, effective_to date, is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), plan_name varchar(100) not null, notes varchar(500), primary key (id)) engine=InnoDB;
create table lease_rate (base_rate decimal(10,2) not null, has_airport_license bit not null, mileage_rate decimal(10,4) not null, id bigint not null auto_increment, plan_id bigint not null, cab_type enum ('HANDICAP_VAN','SEDAN') not null, day_of_week enum ('FRIDAY','MONDAY','SATURDAY','SUNDAY','THURSDAY','TUESDAY','WEDNESDAY') not null, shift_type enum ('DAY','NIGHT') not null, notes varchar(200), primary key (id)) engine=InnoDB;
create table lease_rate_overrides (end_date date, is_active bit not null, lease_rate decimal(10,2) not null, priority integer not null, start_date date not null, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), day_of_week varchar(20), shift_type varchar(20), cab_number varchar(50), created_by varchar(50), owner_driver_number varchar(50) not null, updated_by varchar(50), notes varchar(500), primary key (id)) engine=InnoDB;
create table merchant2cab (end_date date, start_date date not null, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), shift varchar(10) not null, cab_number varchar(20) not null, created_by varchar(100), merchant_number varchar(100) not null, updated_by varchar(100), notes varchar(500), primary key (id)) engine=InnoDB;
create table mileage_records (mileage_a decimal(10,3), mileage_b decimal(10,3), mileage_c decimal(10,3), shift_hours decimal(5,2), total_mileage decimal(10,3), created_at datetime(6) not null, id bigint not null auto_increment, logoff_time datetime(6), logon_time datetime(6) not null, updated_at datetime(6) not null, upload_date datetime(6), cab_number varchar(50) not null, driver_number varchar(50), upload_batch_id varchar(100), uploaded_by varchar(100), upload_filename varchar(255), primary key (id)) engine=InnoDB;
create table one_time_expense (amount decimal(10,2) not null, expense_date date not null, is_reimbursable bit, is_reimbursed bit, reimbursed_date date, attribute_type_id bigint, cab_id bigint, created_at datetime(6) not null, driver_id bigint, entity_id bigint, expense_category_id bigint, id bigint not null auto_increment, owner_id bigint, shift_profile_id bigint, specific_person_id bigint, specific_shift_id bigint, updated_at datetime(6), shift_type enum ('DAY','NIGHT'), entity_type enum ('CAB','COMPANY','DRIVER','OWNER','SHIFT'), paid_by enum ('COMPANY','DRIVER','OWNER','THIRD_PARTY') not null, responsible_party enum ('COMPANY','DRIVER','OWNER','SHARED'), application_type enum ('ALL_ACTIVE_SHIFTS','ALL_DRIVERS','ALL_OWNERS','SHIFTS_WITH_ATTRIBUTE','SHIFT_PROFILE','SPECIFIC_PERSON','SPECIFIC_SHIFT'), invoice_number varchar(100), name varchar(200) not null, vendor varchar(200), receipt_url varchar(500), description varchar(1000), notes varchar(1000), primary key (id)) engine=InnoDB;
create table other_revenue (amount decimal(10,2) not null, payment_date date, revenue_date date not null, attribute_type_id bigint, cab_id bigint, created_at datetime(6) not null, driver_id bigint, entity_id bigint not null, id bigint not null auto_increment, owner_id bigint, revenue_category_id bigint not null, shift_id bigint, shift_profile_id bigint, specific_person_id bigint, specific_shift_id bigint, updated_at datetime(6), application_type enum ('ALL_ACTIVE_SHIFTS','ALL_DRIVERS','ALL_OWNERS','SHIFTS_WITH_ATTRIBUTE','SHIFT_PROFILE','SPECIFIC_PERSON','SPECIFIC_SHIFT'), payment_method varchar(100), reference_number varchar(100), description varchar(1000), notes varchar(1000), entity_type enum ('CAB','COMPANY','DRIVER','OWNER','SHIFT') not null, payment_status enum ('CANCELLED','PAID','PENDING','PROCESSING') not null, revenue_type enum ('ADJUSTMENT','BONUS','COMMISSION','CREDIT','INCENTIVE','OTHER','REFERRAL','REFUND','REIMBURSEMENT') not null, primary key (id)) engine=InnoDB;
create table payment (amount decimal(10,2) not null, payment_date date not null, created_at datetime(6) not null, created_by bigint not null, customer_id bigint not null, id bigint not null auto_increment, invoice_id bigint not null, payment_batch_id bigint, payment_method_id bigint not null, posted_at datetime(6), posted_by bigint, statement_id bigint not null, updated_at datetime(6), updated_by bigint, status varchar(20) not null, account_id varchar(50) not null, payment_method varchar(50), payment_number varchar(50) not null, reference_number varchar(100), notes TEXT, primary key (id)) engine=InnoDB;
create table payment_batch (actual_payments_made decimal(10,2), batch_date date not null, payment_count integer not null, period_end date not null, period_start date not null, total_amount decimal(10,2) not null, created_at datetime(6) not null, created_by bigint not null, id bigint not null auto_increment, posted_at datetime(6), posted_by bigint, processed_at datetime(6), processed_by bigint, updated_at datetime(6), updated_by bigint, status varchar(20) not null, batch_number varchar(50) not null, batch_name varchar(255), reconciliation_notes TEXT, statement_ids TEXT, primary key (id)) engine=InnoDB;
create table payment_method (display_order integer, is_active bit not null, is_automatic bit not null, requires_bank_details bit not null, requires_reference bit not null, id bigint not null auto_increment, method_code varchar(20) not null, method_name varchar(100) not null, primary key (id)) engine=InnoDB;
create table recurring_expense (amount decimal(10,2) not null, effective_from date not null, effective_to date, is_active bit, is_auto_generated bit, attribute_cost_id bigint, attribute_type_id bigint, cab_id bigint, created_at datetime(6) not null, driver_id bigint, entity_id bigint, expense_category_id bigint, generation_date datetime(6), id bigint not null auto_increment, owner_id bigint, shift_id bigint, shift_profile_id bigint, source_rule_id bigint, specific_person_id bigint, specific_shift_id bigint, updated_at datetime(6), shift_type enum ('DAY','NIGHT'), billing_method enum ('DAILY','MONTHLY','PER_SHIFT') not null, entity_type enum ('CAB','COMPANY','DRIVER','OWNER','SHIFT'), application_type_enum varchar(30), notes varchar(500), primary key (id)) engine=InnoDB;
create table recurring_expense_auto_creation (created_at datetime(6) not null, expense_category_rule_id bigint not null, id bigint not null auto_increment, recurring_expense_id bigint not null, creation_type enum ('AUTO_MATCHED','BULK_CONFIGURED','MANUAL') not null, created_by varchar(100), matching_snapshot jsonb, primary key (id)) engine=InnoDB;
create table revenue (amount decimal(10,2) not null, created_at datetime(6) not null, id bigint not null auto_increment, segment_id bigint, shift_log_id bigint not null, timestamp datetime(6) not null, updated_at datetime(6), payment_method enum ('CASH','CHARGE_ACCOUNT','CHECK','CREDIT_CARD','DEBIT_CARD','DIGITAL_WALLET','MOBILE_APP','OTHER') not null, revenue_type enum ('AIRPORT_PICKUP','CHARGE_ACCOUNT','CREDIT_CARD','EXTRA_PASSENGER','LUGGAGE_FEE','OTHER','TIP','TOLL_REIMBURSEMENT','TRIP_FARE','WAITING_CHARGE') not null, customer_account varchar(50), customer_name varchar(100), reference_number varchar(100), description varchar(500), primary key (id)) engine=InnoDB;
create table revenue_category (is_active bit, created_at DATETIME(6) not null, id bigint not null auto_increment, shift_profile_id bigint, specific_driver_id bigint, specific_person_id bigint, specific_shift_id bigint, updated_at DATETIME(6), applies_to enum ('CAB','COMPANY','DRIVER','OWNER','SHIFT') not null, category_type enum ('FIXED','VARIABLE') not null, application_type VARCHAR(30) not null, category_code varchar(50) not null, category_name varchar(100) not null, description varchar(500), primary key (id)) engine=InnoDB;
create table shift_expense (amount decimal(10,2) not null, created_at datetime(6) not null, id bigint not null auto_increment, segment_id bigint, shift_log_id bigint not null, timestamp datetime(6) not null, updated_at datetime(6), paid_by enum ('COMPANY','DRIVER','OWNER') not null, responsible_party enum ('COMPANY','DRIVER','OWNER','SHARED'), expense_type enum ('ACCIDENT_DAMAGE','CAR_WASH','CLEANING','DISPATCH_FEE','FUEL','INSPECTION','INSURANCE','INTERNET_CHARGE','LICENSE_RENEWAL','MAINTENANCE','OIL_CHANGE','OTHER','PARKING','REGISTRATION','TICKET_FINE','TIRE_REPLACEMENT','TOLL') not null, vendor varchar(100), description varchar(500), receipt_url varchar(500), primary key (id)) engine=InnoDB;
create table shift_log (airport_trip_count integer default 0 not null, driver_earnings decimal(10,2), end_meter_reading decimal(10,2), lease_base_rate decimal(10,2), lease_mileage_charge decimal(10,2), lease_mileage_rate decimal(10,4), lease_total_amount decimal(10,2), log_date date not null, net_revenue decimal(10,2), owner_earnings decimal(10,2), start_meter_reading decimal(10,2), total_expenses decimal(10,2), total_lease_amount decimal(10,2), total_miles decimal(10,2), total_revenue decimal(10,2), cab_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, owner_id bigint not null, settled_at datetime(6), shift_id bigint not null, updated_at datetime(6), settlement_status enum ('DISPUTED','PENDING','SETTLED') not null, lease_plan_snapshot varchar(200), notes varchar(1000), primary key (id)) engine=InnoDB;
create table shift_ownership (acquisition_price decimal(10,2), end_date date, sale_price decimal(10,2), start_date date not null, created_at datetime(6) not null, id bigint not null auto_increment, owner_id bigint not null, shift_id bigint not null, transferred_to_driver_id bigint, acquisition_type enum ('INHERITANCE','INITIAL_ASSIGNMENT','PURCHASE','TRANSFER'), notes varchar(500), primary key (id)) engine=InnoDB;
create table shift_profile (display_order integer, has_airport_license bit, is_active bit, is_system_profile bit, usage_count integer, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), color_code varchar(10), cab_type enum ('HANDICAP_VAN','SEDAN'), share_type enum ('NON_VOTING_SHARE','VOTING_SHARE'), shift_type enum ('DAY','NIGHT'), category varchar(50), profile_code varchar(50) not null, created_by varchar(100), profile_name varchar(100) not null, updated_by varchar(100), description varchar(500), primary key (id)) engine=InnoDB;
create table shift_profile_assignment (end_date date, start_date date not null, created_at datetime(6) not null, id bigint not null auto_increment, profile_id bigint not null, shift_id bigint not null, assigned_by varchar(100), reason varchar(500), primary key (id)) engine=InnoDB;
create table shift_profile_attribute (is_required bit, attribute_type_id bigint not null, id bigint not null auto_increment, profile_id bigint not null, expected_value varchar(255), primary key (id)) engine=InnoDB;
create table shift_status_history (effective_from date not null, effective_to date, is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, shift_id bigint not null, changed_by varchar(100), reason varchar(500), primary key (id)) engine=InnoDB;
create table statement_audit_log (changed_at datetime(6) not null, changed_by bigint not null, id bigint not null auto_increment, statement_id bigint not null, new_status varchar(20), previous_status varchar(20), change_type varchar(50) not null, change_description TEXT, changed_fields JSON, reason TEXT, primary key (id)) engine=InnoDB;
create table statement_payment (amount decimal(10,2) not null, payment_date date not null, created_at datetime(6) not null, created_by bigint, id bigint not null auto_increment, payment_batch_id bigint, payment_method_id bigint not null, person_id bigint not null, posted_at datetime(6), posted_by bigint, statement_id bigint not null, updated_at datetime(6), updated_by bigint, person_type varchar(20) not null, status varchar(20) not null, payment_number varchar(50) not null, reference_number varchar(100), notes TEXT, person_name varchar(255), primary key (id)) engine=InnoDB;
create table statements (net_due decimal(38,2), paid_amount decimal(38,2), period_from date, period_to date, previous_balance decimal(38,2), total_expenses decimal(38,2), total_one_time_expenses decimal(38,2), total_recurring_expenses decimal(38,2), total_revenues decimal(38,2), created_at datetime(6), generated_date datetime(6), id bigint not null auto_increment, person_id bigint, created_by varchar(255), line_items_json LONGTEXT, person_name varchar(255), person_type varchar(255), status enum ('DRAFT','FINALIZED','PAID'), primary key (id)) engine=InnoDB;
create table tax_category_assignment (assigned_at date not null, is_active bit not null, unassigned_at date, created_at datetime(6) not null, expense_category_id bigint not null, id bigint not null auto_increment, tax_type_id bigint not null, updated_at datetime(6), notes varchar(500), primary key (id)) engine=InnoDB;
create table tax_rate (effective_from date not null, effective_to date, is_active bit not null, rate decimal(8,4) not null, created_at datetime(6) not null, id bigint not null auto_increment, tax_type_id bigint not null, updated_at datetime(6), notes varchar(500), primary key (id)) engine=InnoDB;
create table tax_type (is_active bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), code varchar(30) not null, name varchar(100) not null, description varchar(500), primary key (id)) engine=InnoDB;
create table tenant_config (taxicaller_company_id integer, created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), tenant_id varchar(63) not null, company_name varchar(100), taxicaller_api_key varchar(100), taxicaller_base_url varchar(255), primary key (id)) engine=InnoDB;
create table user (is_active bit, created_at datetime(6) not null, driver_id bigint, id bigint not null auto_increment, updated_at datetime(6), phone varchar(20), role enum ('ACCOUNTANT','ADMIN','DISPATCHER','DRIVER','MANAGER','SUPER_ADMIN','VIEWER') not null, first_name varchar(50), last_name varchar(50), username varchar(50) not null, email varchar(100), password varchar(255) not null, primary key (id)) engine=InnoDB;
create index idx_charge_customer on account_charge (customer_id);
create index idx_charge_date on account_charge (trip_date);
create index idx_charge_job_code on account_charge (job_code);
create index idx_charge_paid on account_charge (is_paid);
create index idx_charge_cab on account_charge (cab_id);
create index idx_charge_driver on account_charge (driver_id);
create index idx_charge_account_id on account_charge (account_id);
create index idx_charge_invoice on account_charge (invoice_id);
alter table account_charge add constraint uk_account_charge_trip unique (account_id, cab_id, driver_id, trip_date, start_time, job_code);
create index idx_credit_customer on account_credit (customer_id);
create index idx_credit_account on account_credit (account_id);
create index idx_credit_date on account_credit (created_date);
alter table account_customer add constraint UK_sj59pfqrjuomlkq3xb7oog18 unique (company_name);
create index idx_airport_cab_number on airport_trips (cab_number);
create index idx_airport_trip_date on airport_trips (trip_date);
create index idx_airport_upload_batch on airport_trips (upload_batch_id);
alter table airport_trips add constraint uk_airport_cab_date unique (cab_number, trip_date);
create index idx_attribute_cost_attribute_type on attribute_cost (attribute_type_id);
create index idx_attribute_cost_effective_from on attribute_cost (effective_from);
create index idx_attribute_cost_effective_to on attribute_cost (effective_to);
create index idx_attribute_cost_date_range on attribute_cost (effective_from, effective_to);
alter table attribute_cost add constraint uq_attribute_cost_date_range unique (attribute_type_id, effective_from);
create index idx_cab_owner_driver on cab (owner_driver_id);
alter table cab add constraint UK_9uo97s1kqahu8weayc2mer0g7 unique (cab_number);
create index idx_attr_type_active on cab_attribute_type (is_active);
create index idx_attr_type_category on cab_attribute_type (category);
alter table cab_attribute_type add constraint UK_f8u04nfycn937odaoghs6qsy7 unique (attribute_code);
create index idx_attr_val_cab on cab_attribute_value (cab_id);
create index idx_attr_val_type on cab_attribute_value (attribute_type_id);
create index idx_attr_val_dates on cab_attribute_value (start_date, end_date);
create index idx_attr_val_cab_type on cab_attribute_value (cab_id, attribute_type_id);
create index idx_attr_val_current on cab_attribute_value (cab_id, end_date);
create index idx_cab_owner_cab_id on cab_owner_history (cab_id);
create index idx_cab_owner_driver_id on cab_owner_history (owner_driver_id);
create index idx_cab_owner_start_date on cab_owner_history (start_date);
create index idx_shift_owner on cab_shift (current_owner_id);
create index idx_shift_status on cab_shift (status);
alter table cab_shift add constraint UKi0ir3eo9jchximuqboie0nqkr unique (cab_id, shift_type);
create index idx_cca_commission_type on commission_category_assignment (commission_type_id);
create index idx_cca_revenue_cat on commission_category_assignment (revenue_category_id);
create index idx_cca_active on commission_category_assignment (is_active);
create index idx_comm_rate_type on commission_rate (commission_type_id);
create index idx_comm_rate_active on commission_rate (is_active);
create index idx_comm_rate_effective on commission_rate (effective_from, effective_to);
create index idx_commission_type_active on commission_type (is_active);
alter table commission_type add constraint UK_ejteg69fdpv6mlyquodlm6eu7 unique (code);
create index idx_cc_transaction_date on credit_card_transaction (transaction_date);
create index idx_cc_settlement_date on credit_card_transaction (settlement_date);
create index idx_cc_driver_number on credit_card_transaction (driver_number);
create index idx_cc_cab_number on credit_card_transaction (cab_number);
create index idx_cc_status on credit_card_transaction (transaction_status);
create index idx_cc_settled on credit_card_transaction (is_settled);
create index idx_cc_merchant_terminal on credit_card_transaction (merchant_id, terminal_id);
create index idx_cc_upload_batch on credit_card_transaction (upload_batch_id);
create index idx_cc_auth_code on credit_card_transaction (authorization_code);
create index idx_cc_job_id on credit_card_transaction (job_id);
alter table credit_card_transaction add constraint uk_cc_transaction_primary unique (terminal_id, authorization_code, amount, transaction_date, transaction_time);
alter table credit_card_transaction add constraint uk_cc_transaction_id unique (transaction_id);
alter table credit_card_transaction add constraint uk_cc_transaction_secondary unique (merchant_id, terminal_id, cab_number, amount, transaction_date, transaction_time);
create index idx_driver_status on driver (status);
create index idx_driver_name on driver (last_name, first_name);
alter table driver add constraint UK_r4o2ei511ku0f8o7anh7g034 unique (driver_number);
alter table driver add constraint UK_1a5ifv9d7c1kcxvpu226ckim4 unique (username);
create index idx_segment_log on driver_segment (shift_log_id, sequence_number);
create index idx_segment_driver on driver_segment (driver_id, start_time);
create index idx_category_type on expense_category (category_type);
create index idx_category_active on expense_category (is_active);
alter table expense_category add constraint UK_lgmuh3h5v8eiw6ciopvh1t0fp unique (category_code);
create index idx_ecr_category on expense_category_rule (expense_category_id);
create index idx_ecr_mode on expense_category_rule (configuration_mode);
create index idx_ecr_share_rule on expense_category_rule (has_share_type_rule);
create index idx_ecr_airport_rule on expense_category_rule (has_airport_license_rule);
alter table expense_category_rule add constraint UK_acq875wnbh78dlm14yj3d973g unique (expense_category_id);
alter table invoice add constraint UK_t6xkdjx1qtd5whp2iljdfn2yj unique (invoice_number);
create index idx_item_rate_active on item_rate (is_active);
create index idx_item_rate_unit_type on item_rate (unit_type);
create index idx_item_rate_effective_date on item_rate (effective_from, effective_to);
create index idx_item_rate_override_item on item_rate_override (item_rate_id);
create index idx_item_rate_override_owner_cab on item_rate_override (owner_driver_number, cab_number);
create index idx_item_rate_override_dates on item_rate_override (start_date, end_date);
create index idx_item_rate_override_active on item_rate_override (is_active);
create index idx_plan_dates on lease_plan (effective_from, effective_to);
create index idx_plan_active on lease_plan (is_active);
create index idx_rate_lookup on lease_rate (cab_type, has_airport_license, shift_type, day_of_week);
alter table lease_rate add constraint UK52malnbsujq9c1lnafs7r785r unique (plan_id, cab_type, has_airport_license, shift_type, day_of_week);
create index idx_owner_cab on lease_rate_overrides (owner_driver_number, cab_number);
create index idx_dates on lease_rate_overrides (start_date, end_date);
create index idx_active on lease_rate_overrides (is_active);
create index idx_cab_number on merchant2cab (cab_number);
create index idx_merchant_number on merchant2cab (merchant_number);
create index idx_active_mappings on merchant2cab (cab_number, end_date);
create index idx_cab_shift on merchant2cab (cab_number, shift);
alter table merchant2cab add constraint uk_cab_merchant_active unique (cab_number, merchant_number, start_date, shift);
create index idx_mileage_cab_number on mileage_records (cab_number);
create index idx_mileage_driver_number on mileage_records (driver_number);
create index idx_mileage_logon_time on mileage_records (logon_time);
create index idx_mileage_upload_batch on mileage_records (upload_batch_id);
create index idx_onetime_category on one_time_expense (expense_category_id);
create index idx_onetime_entity on one_time_expense (entity_type, entity_id);
create index idx_onetime_date on one_time_expense (expense_date);
create index idx_onetime_paid_by on one_time_expense (paid_by);
create index idx_onetime_shift_type on one_time_expense (shift_type);
create index idx_revenue_category on other_revenue (revenue_category_id);
create index idx_revenue_entity on other_revenue (entity_type, entity_id);
create index idx_revenue_date on other_revenue (revenue_date);
create index idx_revenue_type on other_revenue (revenue_type);
create index idx_revenue_payment_status on other_revenue (payment_status);
create index idx_other_revenue_app_type on other_revenue (application_type);
create index idx_other_revenue_shift_profile on other_revenue (shift_profile_id);
create index idx_other_revenue_specific_shift on other_revenue (specific_shift_id);
create index idx_other_revenue_specific_person on other_revenue (specific_person_id);
create index idx_other_revenue_attribute_type on other_revenue (attribute_type_id);
create index idx_other_revenue_app_type_date on other_revenue (application_type, revenue_date);
alter table payment add constraint UK_k8ietisjrevcrs31m339ms6v3 unique (payment_number);
alter table payment_batch add constraint UK_3wwqwmv32fftkc629vr29n98 unique (batch_number);
create index idx_recurring_category on recurring_expense (expense_category_id);
create index idx_recurring_entity on recurring_expense (entity_type, entity_id);
create index idx_recurring_dates on recurring_expense (effective_from, effective_to);
create index idx_recurring_active on recurring_expense (is_active);
create index idx_recurring_shift_type on recurring_expense (shift_type);
create index idx_reac_rule on recurring_expense_auto_creation (expense_category_rule_id);
create index idx_reac_expense on recurring_expense_auto_creation (recurring_expense_id);
create index idx_reac_type on recurring_expense_auto_creation (creation_type);
create index idx_reac_created on recurring_expense_auto_creation (created_at);
create index idx_revenue_log on revenue (shift_log_id, timestamp);
create index idx_revenue_type on revenue (revenue_type, timestamp);
create index idx_revenue_payment on revenue (payment_method, reference_number);
create index idx_revenue_category_type on revenue_category (category_type);
create index idx_revenue_category_active on revenue_category (is_active);
create index idx_revenue_category_applies_to on revenue_category (applies_to);
alter table revenue_category add constraint UK_noxnvvqrc6r28u53ej035kkub unique (category_code);
create index idx_expense_log on shift_expense (shift_log_id, timestamp);
create index idx_expense_type on shift_expense (expense_type, timestamp);
create index idx_expense_paid_by on shift_expense (paid_by, timestamp);
create index idx_log_date on shift_log (log_date);
create index idx_owner_date on shift_log (owner_id, log_date);
create index idx_settlement on shift_log (settlement_status, log_date);
alter table shift_log add constraint UKct757lpgvlt30cmnj3dsijysg unique (cab_id, shift_id, log_date);
create index idx_shift_owner on shift_ownership (shift_id, owner_id);
create index idx_ownership_dates on shift_ownership (shift_id, start_date, end_date);
create index idx_profile_code on shift_profile (profile_code);
create index idx_profile_active on shift_profile (is_active);
create index idx_profile_category on shift_profile (category);
create index idx_profile_cab_type on shift_profile (cab_type);
create index idx_profile_share_type on shift_profile (share_type);
create index idx_profile_shift_type on shift_profile (shift_type);
create index idx_profile_system on shift_profile (is_system_profile);
alter table shift_profile add constraint UK_hnjgvilj0eo329tses8e8hgtk unique (profile_code);
create index idx_assignment_shift on shift_profile_assignment (shift_id);
create index idx_assignment_profile on shift_profile_assignment (profile_id);
create index idx_assignment_dates on shift_profile_assignment (start_date, end_date);
create index idx_assignment_active on shift_profile_assignment (shift_id, end_date);
alter table shift_profile_assignment add constraint uk_shift_active_profile unique (shift_id, end_date);
create index idx_profile_attr_profile on shift_profile_attribute (profile_id);
create index idx_profile_attr_type on shift_profile_attribute (attribute_type_id);
alter table shift_profile_attribute add constraint UK64icxt052pdj7vpsx8nereukt unique (profile_id, attribute_type_id);
create index idx_shift_status_shift_id on shift_status_history (shift_id);
create index idx_shift_status_dates on shift_status_history (effective_from, effective_to);
create index idx_shift_status_active on shift_status_history (shift_id, is_active, effective_from, effective_to);
alter table statement_payment add constraint UK_c0ge8qhuhw6tqfm9mkq7nq217 unique (payment_number);
create index idx_tca_tax_type on tax_category_assignment (tax_type_id);
create index idx_tca_expense_cat on tax_category_assignment (expense_category_id);
create index idx_tca_active on tax_category_assignment (is_active);
create index idx_tax_rate_type on tax_rate (tax_type_id);
create index idx_tax_rate_active on tax_rate (is_active);
create index idx_tax_rate_effective on tax_rate (effective_from, effective_to);
create index idx_tax_type_active on tax_type (is_active);
alter table tax_type add constraint UK_pexforeg2sel6ehiphmhetgjj unique (code);
alter table tenant_config add constraint UK_ef8qgyim87qokmrbasb9irfog unique (tenant_id);
create index idx_user_username on user (username);
create index idx_user_email on user (email);
create index idx_user_role on user (role);
alter table user add constraint UK_4yaf6tjm0jduantayvd4bqts8 unique (driver_id);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table account_charge add constraint FKa6dph3i3nmmog7p3lr8cbbmta foreign key (customer_id) references account_customer (id);
alter table account_charge add constraint FKt18hj6w8ypo0o5rx4bc6b74f0 foreign key (cab_id) references cab (id);
alter table account_charge add constraint FKa63qjauxepojpta6vcpampuks foreign key (driver_id) references driver (id);
alter table account_credit add constraint FK5r7qj9eqrhqn7xebm2kbnm5sw foreign key (customer_id) references account_customer (id);
alter table attribute_cost add constraint FKpnrwvxv14y5amjor187ieto7r foreign key (attribute_type_id) references cab_attribute_type (id);
alter table cab add constraint FK5cl0n7aw9o2mg1ana74wgqakt foreign key (owner_driver_id) references driver (id);
alter table cab_attribute_value add constraint FKs2w8arr7gbef1lvop7ae7fhnb foreign key (attribute_type_id) references cab_attribute_type (id);
alter table cab_attribute_value add constraint FK1i3ky20qo50j77b18i1ufswfs foreign key (cab_id) references cab (id);
alter table cab_attribute_value add constraint FK1v1vjekndw2w4cctc7caoa562 foreign key (shift_id) references cab_shift (id);
alter table cab_owner_history add constraint FKch956x1c6367u1es133tccyj0 foreign key (cab_id) references cab (id);
alter table cab_owner_history add constraint FKefomj9nwg3txbsx8b4yoeb7af foreign key (owner_driver_id) references driver (id);
alter table cab_shift add constraint FKrtxsa593tov5cj6rdgog4s5m3 foreign key (cab_id) references cab (id);
alter table cab_shift add constraint FKtkwg7vchrrwwjn4va6uof9ws5 foreign key (current_owner_id) references driver (id);
alter table cab_shift add constraint FKqyt6f9kr19ax0ny13bsfo34um foreign key (current_profile_id) references shift_profile (id);
alter table commission_category_assignment add constraint FK9t423kn370te63vkg5f5a8rp1 foreign key (commission_type_id) references commission_type (id);
alter table commission_category_assignment add constraint FKthm0glwyq6y47js467oqylg0e foreign key (revenue_category_id) references revenue_category (id);
alter table commission_rate add constraint FK28qu0agw3drsrq4ktc5m9cyju foreign key (commission_type_id) references commission_type (id);
alter table driver_segment add constraint FK72akpe1v4auh39emf1o2i8dku foreign key (driver_id) references driver (id);
alter table driver_segment add constraint FK8n2gdbn0nmu1r3qxee1p7ebuw foreign key (shift_log_id) references shift_log (id);
alter table expense_category add constraint FKhirnu40hqnybhqkiyg6tes192 foreign key (specific_driver_id) references driver (id);
alter table expense_category add constraint FK40pl3c0fsb571m2nu6pt1rxsv foreign key (specific_owner_id) references driver (id);
alter table expense_category add constraint FKcmeuh75ibdr05aaahtt8u1y foreign key (specific_shift_id) references cab_shift (id);
alter table expense_category_rule add constraint FK99mj8ymiix9r3vntxve3pgl3y foreign key (expense_category_id) references expense_category (id);
alter table invoice add constraint FK5wwwt3d22ypro0uu0qe68ytk6 foreign key (customer_id) references account_customer (id);
alter table invoice_line_item add constraint FK34c5q8q9ektmwqdcbd923dnx7 foreign key (charge_id) references account_charge (id);
alter table invoice_line_item add constraint FK4560gqjs1jn62cp4govj4akb3 foreign key (invoice_id) references invoice (id);
alter table item_rate_override add constraint FKdkope52xk3nxpexuh7bky0s4o foreign key (item_rate_id) references item_rate (id);
alter table lease_expense add constraint FKjsfkq1ta3xippq4894tglo3b1 foreign key (plan_id) references lease_plan (id);
alter table lease_expense add constraint FK5ji9frfi2bfrxd7tv8fxn3i20 foreign key (rate_id) references lease_rate (id);
alter table lease_rate add constraint FK1n8jb2hpdgvxn021rf5vph4i7 foreign key (plan_id) references lease_plan (id);
alter table one_time_expense add constraint FK2n2ih5oqymafsn3a24skr1v7t foreign key (cab_id) references cab (id);
alter table one_time_expense add constraint FK5hy1m50ve8bvgbv2fcqj5q9mb foreign key (driver_id) references driver (id);
alter table one_time_expense add constraint FK3j4cyadbpnoxv5nshpnjhq2vc foreign key (expense_category_id) references expense_category (id);
alter table one_time_expense add constraint FKio0fjipe7fnw0kxkc735d7qol foreign key (owner_id) references driver (id);
alter table other_revenue add constraint FKd6ibfaaqjtgqrvbbxg8j9q1tw foreign key (cab_id) references cab (id);
alter table other_revenue add constraint FKhg49qg5n1m21fpr2w6mhqy9g3 foreign key (revenue_category_id) references revenue_category (id);
alter table other_revenue add constraint FK9od0jqpsy6tbf0ly8nfm16y5q foreign key (driver_id) references driver (id);
alter table other_revenue add constraint FK3vf97sqn64fdym53dn26dipov foreign key (owner_id) references driver (id);
alter table other_revenue add constraint FKlpbfal23gxklbjq00bkuggmom foreign key (shift_id) references cab_shift (id);
alter table payment add constraint FKfnf68v6dj7m6a678aqy1a4ikf foreign key (payment_batch_id) references payment_batch (id);
alter table payment add constraint FKjii2n6db6cje3km5ybsbgo8cl foreign key (payment_method_id) references payment_method (id);
alter table payment add constraint FKsnndjhy5bo6cun3993sj2fk4t foreign key (statement_id) references invoice (id);
alter table recurring_expense add constraint FKh70dxb3h1wg6d97bbf90xefit foreign key (cab_id) references cab (id);
alter table recurring_expense add constraint FK5rrxdva670ocvpm7segorwkpi foreign key (driver_id) references driver (id);
alter table recurring_expense add constraint FK1vkknq8hfn8u6hjmpvvgq0abr foreign key (expense_category_id) references expense_category (id);
alter table recurring_expense add constraint FK765ihg2yqa9ac72rbdq3evytt foreign key (owner_id) references driver (id);
alter table recurring_expense add constraint FKgxcu8ksqljfigjaq63qvy90mi foreign key (shift_id) references cab_shift (id);
alter table recurring_expense_auto_creation add constraint FKckvnd2ruklv1ynvtjk8gudb9m foreign key (expense_category_rule_id) references expense_category_rule (id);
alter table recurring_expense_auto_creation add constraint FK1gm60bdv4p6jt1vrtm7006u2e foreign key (recurring_expense_id) references recurring_expense (id);
alter table revenue add constraint FKdl7cejkiix1dj3y0vm12v0njm foreign key (segment_id) references driver_segment (id);
alter table revenue add constraint FK6idc0u9fy8hvhfayb4ac0utj1 foreign key (shift_log_id) references shift_log (id);
alter table revenue_category add constraint FKgpwpsdvulew8mpvps88227hhu foreign key (specific_driver_id) references driver (id);
alter table revenue_category add constraint FK4wnwve5hp6j9i2el1k37h6lxb foreign key (specific_person_id) references driver (id);
alter table revenue_category add constraint FKm1hdw85xjqapjlkyjn1vq0a7h foreign key (specific_shift_id) references cab_shift (id);
alter table shift_expense add constraint FK846m12objwe5blmyga7bu7xlp foreign key (segment_id) references driver_segment (id);
alter table shift_expense add constraint FKo9ac7k6jd1vrukiyo42c0hram foreign key (shift_log_id) references shift_log (id);
alter table shift_log add constraint FKrcnxqtxjit4k8c0gserii786 foreign key (cab_id) references cab (id);
alter table shift_log add constraint FKc8qfr06fy446w17hqp5d2kbm4 foreign key (owner_id) references driver (id);
alter table shift_log add constraint FKj7d3cqp96g89al1tsqykhvkkq foreign key (shift_id) references cab_shift (id);
alter table shift_ownership add constraint FK4y0o6m4rfmrcmfqnmrvws45r2 foreign key (owner_id) references driver (id);
alter table shift_ownership add constraint FK8hd78e0dh6fbmg92sf2hukwfs foreign key (shift_id) references cab_shift (id);
alter table shift_ownership add constraint FKocm978n37ip19xcpas8yt7qdq foreign key (transferred_to_driver_id) references driver (id);
alter table shift_profile_assignment add constraint FK8k1dbw44iaw2c7jt9corry3r1 foreign key (profile_id) references shift_profile (id);
alter table shift_profile_assignment add constraint FKkfi1e4b4qcagbgo15bqkachto foreign key (shift_id) references cab_shift (id);
alter table shift_profile_attribute add constraint FK9oic9daywgs2no3yktl22bryu foreign key (attribute_type_id) references cab_attribute_type (id);
alter table shift_profile_attribute add constraint FKeat1uvo3woxcqnbcanj67gdtm foreign key (profile_id) references shift_profile (id);
alter table shift_status_history add constraint FKgaidrhbpbgfmddf6s6dmqio77 foreign key (shift_id) references cab_shift (id);
alter table statement_audit_log add constraint FKsx1w22o3hohw9yy7wiirsgv6s foreign key (statement_id) references invoice (id);
alter table statement_payment add constraint FKrnnqx3vak8b8qid2ba9vxb136 foreign key (payment_batch_id) references payment_batch (id);
alter table statement_payment add constraint FKmab9domv2madeu8dbqhw8e9wj foreign key (payment_method_id) references payment_method (id);
alter table tax_category_assignment add constraint FKdd2mftp2ykdillxg56i6jq912 foreign key (expense_category_id) references expense_category (id);
alter table tax_category_assignment add constraint FKefoc0ue31gg1do217u3gfc4qc foreign key (tax_type_id) references tax_type (id);
alter table tax_rate add constraint FKcm85lkmd70pftji6b409p97do foreign key (tax_type_id) references tax_type (id);
alter table user add constraint FKc4heewvadmwpbm330r49pue0j foreign key (driver_id) references driver (id);
