package com.taxi.domain.expense.repository;

import com.taxi.domain.expense.model.ApplicationType;
import com.taxi.domain.expense.model.RecurringExpense;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;

/**
 * Repository for RecurringExpense entity
 */
@Repository
public interface RecurringExpenseRepository extends JpaRepository<RecurringExpense, Long> {

    /**
     * Find all active recurring expenses
     */
    List<RecurringExpense> findByIsActiveTrue();

    /**
     * Find recurring expenses for a specific entity
     */
    List<RecurringExpense> findByEntityTypeAndEntityId(
        RecurringExpense.EntityType entityType, 
        Long entityId
    );

    /**
     * Find active recurring expenses for a specific entity
     */
    @Query("SELECT re FROM RecurringExpense re WHERE re.entityType = :entityType " +
           "AND re.entityId = :entityId AND re.isActive = true")
    List<RecurringExpense> findActiveByEntityTypeAndEntityId(
        @Param("entityType") RecurringExpense.EntityType entityType,
        @Param("entityId") Long entityId
    );

    /**
     * Find recurring expenses effective on a specific date
     */
    @Query("SELECT re FROM RecurringExpense re WHERE re.isActive = true " +
           "AND re.effectiveFrom <= :date " +
           "AND (re.effectiveTo IS NULL OR re.effectiveTo >= :date)")
    List<RecurringExpense> findEffectiveOn(@Param("date") LocalDate date);

    /**
     * Find recurring expenses for entity effective on date
     */
    @Query("SELECT re FROM RecurringExpense re WHERE re.entityType = :entityType " +
           "AND re.entityId = :entityId AND re.isActive = true " +
           "AND re.effectiveFrom <= :date " +
           "AND (re.effectiveTo IS NULL OR re.effectiveTo >= :date)")
    List<RecurringExpense> findEffectiveForEntityOn(
        @Param("entityType") RecurringExpense.EntityType entityType,
        @Param("entityId") Long entityId,
        @Param("date") LocalDate date
    );

    /**
     * Find recurring expenses by category
     */
    @Query("SELECT re FROM RecurringExpense re WHERE re.expenseCategory.id = :categoryId " +
           "AND re.isActive = true")
    List<RecurringExpense> findActiveByExpenseCategoryId(@Param("categoryId") Long categoryId);

    /**
     * Find recurring expenses for date range
     */
    // @Query("SELECT re FROM RecurringExpense re WHERE re.isActive = true " +
    //        "AND ((re.effectiveFrom <= :endDate AND (re.effectiveTo IS NULL OR re.effectiveTo >= :startDate)))")
    // List<RecurringExpense> findEffectiveBetween(
    //     @Param("startDate") LocalDate startDate,
    //     @Param("endDate") LocalDate endDate
    // );

    @Query("SELECT re FROM RecurringExpense re WHERE re.isActive = true " +
       "AND (DATE(re.effectiveFrom) <= :endDate) " +
       "AND (re.effectiveTo IS NULL OR DATE(re.effectiveTo) >= :startDate)")
List<RecurringExpense> findEffectiveBetween(
    @Param("startDate") LocalDate startDate,
    @Param("endDate") LocalDate endDate
);


    /**
     * Find recurring expenses for entity in date range
     */
    @Query("SELECT re FROM RecurringExpense re WHERE re.entityType = :entityType " +
           "AND re.entityId = :entityId " +
           "AND ((re.effectiveFrom <= :endDate AND (re.effectiveTo IS NULL OR re.effectiveTo >= :startDate)))")
    List<RecurringExpense> findForEntityBetween(
        @Param("entityType") RecurringExpense.EntityType entityType,
        @Param("entityId") Long entityId,
        @Param("startDate") LocalDate startDate,
        @Param("endDate") LocalDate endDate
    );

    /**
     * Check if active expense exists for cab + category combination
     */
    @Query("SELECT CASE WHEN COUNT(re) > 0 THEN true ELSE false END " +
           "FROM RecurringExpense re WHERE re.entityType = 'CAB' " +
           "AND re.entityId = :cabId " +
           "AND re.expenseCategory.id = :categoryId " +
           "AND re.isActive = true")
    boolean existsActiveByCabAndCategory(
        @Param("cabId") Long cabId,
        @Param("categoryId") Long categoryId
    );

    /**
     * Find expenses created from a specific category rule
     */
    List<RecurringExpense> findBySourceRuleId(Long sourceRuleId);

    /**
     * Find auto-generated expenses
     */
    @Query("SELECT re FROM RecurringExpense re WHERE re.isAutoGenerated = true " +
           "AND re.sourceRuleId = :ruleId")
    List<RecurringExpense> findAutoGeneratedBySourceRuleId(@Param("ruleId") Long ruleId);

    /**
     * Check if an active recurring expense already exists for a specific shift and attribute cost
     * Used to prevent duplicate expense creation from attribute costs
     */
    @Query("SELECT CASE WHEN COUNT(re) > 0 THEN true ELSE false END " +
           "FROM RecurringExpense re WHERE re.shift.id = :shiftId " +
           "AND re.attributeCostId = :attributeCostId " +
           "AND re.isActive = true")
    boolean existsByShiftAndAttributeCost(
        @Param("shiftId") Long shiftId,
        @Param("attributeCostId") Long attributeCostId
    );

    /**
     * Find recurring expenses by application type within date range
     */
    @Query("SELECT re FROM RecurringExpense re WHERE re.applicationTypeEnum = :applicationType " +
           "AND re.isActive = true " +
           "AND (DATE(re.effectiveFrom) <= :endDate) " +
           "AND (re.effectiveTo IS NULL OR DATE(re.effectiveTo) >= :startDate)")
    List<RecurringExpense> findEffectiveBetweenForApplicationType(
        @Param("applicationType") ApplicationType applicationType,
        @Param("startDate") LocalDate startDate,
        @Param("endDate") LocalDate endDate
    );

    /**
     * Find recurring expenses by application type and shift profile within date range
     */
    @Query("SELECT DISTINCT re FROM RecurringExpense re WHERE re.applicationTypeEnum = :applicationType " +
           "AND re.shiftProfileId = :shiftProfileId " +
           "AND re.isActive = true " +
           "AND (DATE(re.effectiveFrom) <= :endDate) " +
           "AND (re.effectiveTo IS NULL OR DATE(re.effectiveTo) >= :startDate)")
    List<RecurringExpense> findByApplicationTypeAndShiftProfileIdBetween(
        @Param("applicationType") ApplicationType applicationType,
        @Param("shiftProfileId") Long shiftProfileId,
        @Param("startDate") LocalDate startDate,
        @Param("endDate") LocalDate endDate
    );

    /**
     * Find recurring expenses by application type and specific shift within date range
     */
    @Query("SELECT re FROM RecurringExpense re WHERE re.applicationTypeEnum = :applicationType " +
           "AND re.specificShiftId = :specificShiftId " +
           "AND re.isActive = true " +
           "AND (DATE(re.effectiveFrom) <= :endDate) " +
           "AND (re.effectiveTo IS NULL OR DATE(re.effectiveTo) >= :startDate)")
    List<RecurringExpense> findByApplicationTypeAndSpecificShiftIdBetween(
        @Param("applicationType") ApplicationType applicationType,
        @Param("specificShiftId") Long specificShiftId,
        @Param("startDate") LocalDate startDate,
        @Param("endDate") LocalDate endDate
    );

    /**
     * Find recurring expenses by application type and specific person within date range
     */
    @Query("SELECT re FROM RecurringExpense re WHERE re.applicationTypeEnum = :applicationType " +
           "AND re.specificPersonId = :specificPersonId " +
           "AND re.isActive = true " +
           "AND (DATE(re.effectiveFrom) <= :endDate) " +
           "AND (re.effectiveTo IS NULL OR DATE(re.effectiveTo) >= :startDate)")
    List<RecurringExpense> findByApplicationTypeAndSpecificPersonIdBetween(
        @Param("applicationType") ApplicationType applicationType,
        @Param("specificPersonId") Long specificPersonId,
        @Param("startDate") LocalDate startDate,
        @Param("endDate") LocalDate endDate
    );
}
